spring:
  application:
    name: async-worker
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: async-worker

server:
  port: 8085

upload:
  expire-sweep:
    interval-ms: ${UPLOAD_EXPIRE_SWEEP_INTERVAL_MS:300000}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
